// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/anchors/verify": {
            "post": {
                "description": "Verify that two documents are properly linked across channels using cryptographic hashes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verification"
                ],
                "summary": "Verify cross-channel link",
                "parameters": [
                    {
                        "description": "Source and target document info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VerifyAnchorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AnchorVerification"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/transfers/initiate": {
            "post": {
                "description": "Start an inter-government transfer (e.g., Federal → State). Creates document with cryptographic hash.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transfers"
                ],
                "summary": "Initiate cross-channel transfer",
                "parameters": [
                    {
                        "description": "Transfer details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InitiateTransferRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.TransferResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{channel}/document-types": {
            "get": {
                "description": "Get all document types for a channel",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Document Types"
                ],
                "summary": "List document types",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel (union, state, region)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.DocumentType"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new document type template with required/optional fields",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Document Types"
                ],
                "summary": "Register document type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel (union, state, region)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Document type data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateDocumentTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{channel}/document-types/{typeId}": {
            "get": {
                "description": "Get specific document type by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Document Types"
                ],
                "summary": "Get document type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel (union, state, region)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Document type ID",
                        "name": "typeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DocumentType"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Mark document type as inactive (no new documents allowed)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Document Types"
                ],
                "summary": "Deactivate document type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel (union, state, region)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Document type ID",
                        "name": "typeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{channel}/documents": {
            "get": {
                "description": "Search and filter documents with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Query documents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel (union, state, region)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by organization",
                        "name": "organizationId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by document type",
                        "name": "documentTypeId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ACTIVE",
                            "INVALIDATED"
                        ],
                        "type": "string",
                        "description": "Filter by status (ACTIVE, INVALIDATED)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "From date (ISO 8601)",
                        "name": "fromDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "To date (ISO 8601)",
                        "name": "toDate",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum amount",
                        "name": "minAmount",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum amount",
                        "name": "maxAmount",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Has linked document",
                        "name": "hasLinkedDoc",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "OUTGOING",
                            "INCOMING"
                        ],
                        "type": "string",
                        "description": "Link direction",
                        "name": "linkedDirection",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination bookmark",
                        "name": "bookmark",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.QueryResult"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new spending document (contractor payment, equipment, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Create document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel (union, state, region)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Document data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateDocumentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Document"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{channel}/documents/{docId}": {
            "get": {
                "description": "Get specific document by ID with all details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Get document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel (union, state, region)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "docId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Document"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{channel}/documents/{docId}/history": {
            "get": {
                "description": "Get complete transaction history for a document (all versions)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Get document history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel (union, state, region)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "docId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.HistoryEntry"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{channel}/documents/{docId}/invalidate": {
            "post": {
                "description": "Mark document as invalid (immutable - never deleted). Used for error correction.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Invalidate document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel (union, state, region)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "docId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Invalidation reason and correction doc",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InvalidateDocumentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Only creating organization can invalidate",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{channel}/documents/{docId}/linked": {
            "get": {
                "description": "Get document and its cross-channel linked document (if any)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Get document with linked document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel (union, state, region)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "docId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LinkedDocuments"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/{channel}/transfers/acknowledge": {
            "post": {
                "description": "Acknowledge a received cross-channel transfer. Creates linked document on target channel.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transfers"
                ],
                "summary": "Acknowledge transfer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target channel (union, state, region)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Acknowledgment details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AcknowledgeTransferRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.TransferResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "status: healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AcknowledgeTransferRequest": {
            "type": "object",
            "required": [
                "documentTypeId",
                "sourceChannel",
                "sourceDocId",
                "title"
            ],
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "description": {
                    "type": "string"
                },
                "documentTypeId": {
                    "type": "string"
                },
                "sourceChannel": {
                    "type": "string"
                },
                "sourceDocId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.AnchorVerification": {
            "type": "object",
            "properties": {
                "amountMatch": {
                    "type": "boolean"
                },
                "channelMatch": {
                    "type": "boolean"
                },
                "hashMatch": {
                    "type": "boolean"
                },
                "idMatch": {
                    "type": "boolean"
                },
                "isValid": {
                    "type": "boolean"
                },
                "mismatchReason": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sourceAmount": {
                    "type": "number"
                },
                "sourceChannel": {
                    "type": "string"
                },
                "sourceCurrency": {
                    "type": "string"
                },
                "sourceDocId": {
                    "type": "string"
                },
                "sourceHash": {
                    "type": "string"
                },
                "status": {
                    "description": "\"VERIFIED\" or \"MISMATCH\"",
                    "type": "string"
                },
                "targetAmount": {
                    "type": "number"
                },
                "targetChannel": {
                    "type": "string"
                },
                "targetCurrency": {
                    "type": "string"
                },
                "targetDocId": {
                    "type": "string"
                },
                "targetHash": {
                    "type": "string"
                }
            }
        },
        "models.CreateDocumentRequest": {
            "type": "object",
            "required": [
                "documentTypeId",
                "title"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "description": {
                    "type": "string"
                },
                "documentTypeId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.CreateDocumentTypeRequest": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "optionalFields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "requiredFields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.Document": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "channelId": {
                    "type": "string"
                },
                "contentHash": {
                    "type": "string"
                },
                "correctedByDoc": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "Audit trail",
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "description": {
                    "type": "string"
                },
                "documentTypeId": {
                    "type": "string"
                },
                "history": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "invalidReason": {
                    "type": "string"
                },
                "invalidatedAt": {
                    "type": "string"
                },
                "invalidatedBy": {
                    "description": "Invalidation tracking - will be empty strings if not invalidated",
                    "type": "string"
                },
                "linkedChannel": {
                    "type": "string"
                },
                "linkedDirection": {
                    "description": "\"OUTGOING\" or \"INCOMING\" or \"\"",
                    "type": "string"
                },
                "linkedDocHash": {
                    "type": "string"
                },
                "linkedDocId": {
                    "description": "Cross-channel linking (simple fields instead of complex Anchor struct)\nWill be empty strings if not set",
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.DocumentStatus"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                }
            }
        },
        "models.DocumentStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "INVALIDATED"
            ],
            "x-enum-varnames": [
                "StatusActive",
                "StatusInvalidated"
            ]
        },
        "models.DocumentType": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "optionalFields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "organizationId": {
                    "type": "string"
                },
                "requiredFields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "context": {
                    "type": "object",
                    "additionalProperties": true
                },
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.HistoryEntry": {
            "type": "object",
            "properties": {
                "document": {
                    "$ref": "#/definitions/models.Document"
                },
                "isDelete": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                },
                "txId": {
                    "type": "string"
                }
            }
        },
        "models.IDResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.InitiateTransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "documentTypeId",
                "fromChannel",
                "title",
                "toChannel",
                "toOrg"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "description": {
                    "type": "string"
                },
                "documentTypeId": {
                    "type": "string"
                },
                "fromChannel": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "toChannel": {
                    "type": "string"
                },
                "toOrg": {
                    "type": "string"
                }
            }
        },
        "models.InvalidateDocumentRequest": {
            "type": "object",
            "required": [
                "reason"
            ],
            "properties": {
                "correctionDocId": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "models.LinkedDocuments": {
            "type": "object",
            "properties": {
                "document": {
                    "$ref": "#/definitions/models.Document"
                },
                "linkVerified": {
                    "type": "boolean"
                },
                "linkedDocument": {
                    "$ref": "#/definitions/models.Document"
                }
            }
        },
        "models.QueryResult": {
            "type": "object",
            "properties": {
                "bookmark": {
                    "type": "string"
                },
                "documents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Document"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.TransferResult": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string"
                },
                "contentHash": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "linkedDocChannel": {
                    "type": "string"
                },
                "linkedDocHash": {
                    "type": "string"
                },
                "linkedDocId": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.VerifyAnchorRequest": {
            "type": "object",
            "required": [
                "sourceChannel",
                "sourceDocId",
                "targetChannel",
                "targetDocId"
            ],
            "properties": {
                "sourceChannel": {
                    "type": "string"
                },
                "sourceDocId": {
                    "type": "string"
                },
                "targetChannel": {
                    "type": "string"
                },
                "targetDocId": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Health check endpoints",
            "name": "Health"
        },
        {
            "description": "Manage document type templates",
            "name": "Document Types"
        },
        {
            "description": "Create and query spending documents",
            "name": "Documents"
        },
        {
            "description": "Cross-channel inter-government transfers",
            "name": "Transfers"
        },
        {
            "description": "Verify cross-channel links",
            "name": "Verification"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Government Spending Blockchain API",
	Description:      "API for managing government spending documents across Federal, State, and Municipal channels\nUses Hyperledger Fabric blockchain for immutable, transparent spending records",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
